<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-06-10 17:36
=======
# Generated by Django 4.2.20 on 2025-06-13 00:57
>>>>>>> 054d3a9ce22ec65fd7dff4c9b794f2ea25258212

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
<<<<<<< HEAD
from django.db import migrations, models
=======
>>>>>>> 054d3a9ce22ec65fd7dff4c9b794f2ea25258212


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(default='en_attente', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=200)),
                ('description_boutique', models.TextField()),
                ('adresse_commerciale', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=50)),
                ('est_verifie', models.BooleanField(default=False)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.categorie')),
                ('commercant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.detailscommercant')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('type_utilisateur', models.CharField(choices=[('client', 'Client'), ('vendeur', 'Vendeur'), ('administrateur', 'Administrateur')], max_length=15)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('methode_verification', models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10, null=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('est_defaut', models.BooleanField(default=False)),
                ('reference_specification', models.CharField(max_length=50)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detailsclient')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.specificationproduit')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_notification', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('type_mouvement', models.CharField(max_length=30)),
                ('reference_document', models.CharField(blank=True, max_length=50, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.specificationproduit')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.CharField(max_length=255)),
                ('type_image', models.CharField(max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_notification', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.CharField(max_length=255)),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detailsclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.AddField(
            model_name='detailscommercant',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.imageutilisateur'),
        ),
        migrations.AddField(
            model_name='detailscommercant',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='detailsclient',
            name='photo_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.imageutilisateur'),
        ),
        migrations.AddField(
            model_name='detailsclient',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur'),
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.commande')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.specificationproduit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detailsclient'),
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAdmin',
=======
            name='Avis',
>>>>>>> 054d3a9ce22ec65fd7dff4c9b794f2ea25258212
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detailsclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
    ]
