# Generated by Django 5.2.1 on 2025-07-15 12:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('promotional', 'Promotion'), ('newsletter', 'Newsletter'), ('announcement', 'Annonce')], max_length=50)),
                ('target_users', models.CharField(default='all', max_length=50)),
                ('channel', models.CharField(default='email', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmée'), ('active', 'Active'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CritereQualiteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('poids', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.CharField(max_length=255)),
                ('type_image', models.CharField(max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(max_length=100)),
                ('telephone_professionnel', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('taux_commission', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('est_approuve', models.BooleanField(default=False)),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('evaluation', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('technical', 'Technique'), ('system', 'Système'), ('security', 'Sécurité'), ('performance', 'Performance')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Attention'), ('critical', 'Critique')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Résolue'), ('investigating', 'En cours')], default='active', max_length=20)),
                ('affected_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('type_utilisateur', models.CharField(choices=[('client', 'Client'), ('vendeur', 'Vendeur'), ('administrateur', 'Administrateur')], max_length=15)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('methode_verification', models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10, null=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(default='en_attente', max_length=30)),
                ('est_litigieuse', models.BooleanField(default=False)),
                ('raison_litige', models.TextField(blank=True, null=True)),
                ('date_resolution_litige', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detailsclient')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=200)),
                ('description_boutique', models.TextField()),
                ('adresse_commerciale', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=50)),
                ('est_verifie', models.BooleanField(default=False)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.imageutilisateur')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='detailsclient',
            name='photo_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.imageutilisateur'),
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('est_approuve', models.BooleanField(default=False)),
                ('statut_moderation', models.CharField(choices=[('en_attente', 'En attente de modération'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20)),
                ('date_moderation', models.DateTimeField(blank=True, null=True)),
                ('raison_rejet', models.TextField(blank=True, null=True)),
                ('est_visible', models.BooleanField(default=True)),
                ('score_qualite', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('derniere_verification', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.categorie')),
                ('commercant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.detailscommercant')),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='myapp.profilvendeur')),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_moderes', to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_notification', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('target_users', models.CharField(default='all', max_length=50)),
                ('channel', models.CharField(default='push', max_length=20)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.CharField(max_length=255)),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detailsclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detailsclient')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('est_defaut', models.BooleanField(default=False)),
                ('reference_specification', models.CharField(max_length=50)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('type_mouvement', models.CharField(max_length=30)),
                ('reference_document', models.CharField(blank=True, max_length=50, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.specificationproduit')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.commande')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.specificationproduit')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=30, null=True)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='myapp.commande')),
            ],
            options={
                'verbose_name': 'Historique de commande',
                'verbose_name_plural': 'Historiques de commandes',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AddField(
            model_name='profilvendeur',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'type_utilisateur': 'vendeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_vendeur', to='myapp.utilisateur'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='imageutilisateur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur'),
        ),
        migrations.CreateModel(
            name='HistoriqueModerationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_moderation', to='myapp.produit')),
                ('moderateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddField(
            model_name='detailsclient',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur'),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detailsclient')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.specificationproduit')),
            ],
            options={
                'ordering': ['-date_modification'],
                'unique_together': {('client', 'specification')},
            },
        ),
        migrations.CreateModel(
            name='SignalementProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_signalement', models.CharField(choices=[('contenu_inapproprie', 'Contenu inapproprié'), ('fausse_information', 'Fausse information'), ('prix_anormal', 'Prix anormal'), ('image_trompeuse', 'Image trompeuse'), ('spam', 'Spam'), ('violation_droits', 'Violation de droits'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='nouveau', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('action_prise', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='myapp.produit')),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to='myapp.utilisateur')),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_envoyes', to='myapp.utilisateur')),
            ],
            options={
                'ordering': ['-date_signalement'],
                'unique_together': {('produit', 'signaleur')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationQualiteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.criterequaliteproduit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_qualite', to='myapp.produit')),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
            options={
                'unique_together': {('produit', 'critere')},
            },
        ),
    ]
