# Generated by Django 5.2.1 on 2025-05-29 22:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='derniere_connexion',
            new_name='date_modification',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='is_staff',
            new_name='est_verifie',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_inscription',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='id',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='password',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_utilisateur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='methode_verification',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='mot_de_passe',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('client', 'Client'), ('vendeur', 'Vendeur'), ('administrateur', 'Administrateur')], default='Client', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailsclient',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='detailscommercant',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='imageutilisateur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='journaladmin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='commercant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.detailscommercant'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='utilisateurs',
        ),
    ]
