# Generated by Django 5.2.1 on 2025-06-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(max_length=100)),
                ('telephone_professionnel', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('taux_commission', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('est_approuve', models.BooleanField(default=False)),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('evaluation', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'type_utilisateur': 'vendeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_vendeur', to='myapp.utilisateur')),
            ],
        ),
    ]
