# Generated by Django 4.2.20 on 2025-06-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=30, null=True)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='myapp.commande')),
            ],
            options={
                'verbose_name': 'Historique de commande',
                'verbose_name_plural': 'Historiques de commandes',
                'ordering': ['-date_modification'],
            },
        ),
    ]
