# Generated by Django 5.2.1 on 2025-07-12 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CritereQualiteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('poids', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='date_moderation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='derniere_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_approuve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='moderateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_moderes', to='myapp.utilisateur'),
        ),
        migrations.AddField(
            model_name='produit',
            name='raison_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='score_qualite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='produit',
            name='statut_moderation',
            field=models.CharField(choices=[('en_attente', 'En attente de modération'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoriqueModerationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('moderateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_moderation', to='myapp.produit')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationQualiteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.criterequaliteproduit')),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_qualite', to='myapp.produit')),
            ],
            options={
                'unique_together': {('produit', 'critere')},
            },
        ),
        migrations.CreateModel(
            name='SignalementProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_signalement', models.CharField(choices=[('contenu_inapproprie', 'Contenu inapproprié'), ('fausse_information', 'Fausse information'), ('prix_anormal', 'Prix anormal'), ('image_trompeuse', 'Image trompeuse'), ('spam', 'Spam'), ('violation_droits', 'Violation de droits'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='nouveau', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('action_prise', models.TextField(blank=True, null=True)),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to='myapp.utilisateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='myapp.produit')),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_envoyes', to='myapp.utilisateur')),
            ],
            options={
                'ordering': ['-date_signalement'],
                'unique_together': {('produit', 'signaleur')},
            },
        ),
    ]
