# Generated by Django 4.2.20 on 2025-07-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trackingcommande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={'ordering': ['-date_modification']},
        ),
        migrations.AddField(
            model_name='panier',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='panier',
            unique_together={('client', 'specification')},
        ),
    ]
