# Generated by Django 5.2.1 on 2025-06-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_produit_commercant_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeReapprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.IntegerField()),
                ('fournisseur', models.CharField(max_length=200)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('commandee', 'Commandée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('prix_unitaire_commande', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_commande_fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.specificationproduit')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
    ]
