# Generated by Django 5.2.1 on 2025-05-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_utilisateur_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenom',
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table=None,
        ),
    ]
