# Generated by Django 5.2.1 on 2025-07-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_criterequaliteproduit_produit_date_moderation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_resolution_litige',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='est_litigieuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='raison_litige',
            field=models.TextField(blank=True, null=True),
        ),
    ]
