# Generated by Django 5.2.1 on 2025-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_utilisateur_prenom_alter_utilisateur_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
