# Generated by Django 5.2.1 on 2025-06-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_commandereapprovisionnement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandeReapprovisionnement',
        ),
    ]
