# Generated by Django 5.2.1 on 2025-07-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_campaign_systemalert_notification_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.produit'),
        ),
    ]
